
C++ 2.0 (c++11 c++14 c++ 17) 基础功能使用

# + memory 操作

#### `enable_shared_from_this`

相关文章推荐地址：
+ [C++11新特性之十：enable_shared_from_this](https://blog.csdn.net/caoshangpa/article/details/79392878)

> 可以说是为了报活:
因为在异步调用中，存在一个保活机制，异步函数执行的时间点我们是无法确定的，然而异步函数可能会使用到异步调用之前就存在的变量。
为了保证该变量在异步函数执期间一直有效，我们可以传递一个指向自身的share_ptr给异步函数，这样在异步函数执行期间share_ptr所管理的对象就不会析构，所使用的变量也会一直有效了（保活）


<br/>

实例代码:<br/>
错误代码示范:
```cpp
#include <memory>
#include <iostream>

class Bad {
public:
    std::shared_ptr<Bad> getptr() {
        return std::shared_ptr<Bad>(this);
    }
    ~Bad() {
        std::cout << "Bad::~Bad() called" << std::endl;
    }
};

int main() {
    // 错误的示例，每个shared_ptr都认为自己是对象仅有的所有者
    std::shared_ptr<Bad> bp1(new Bad());
    std::shared_ptr<Bad> bp2 = bp1->getptr();
    // 打印bp1和bp2的引用计数
    std::cout << "bp1.use_count() = " << bp1.use_count() << std::endl;
    std::cout << "bp2.use_count() = " << bp2.use_count() << std::endl;
}  // Bad 对象将会被删除两次

运行出现异常：
bp1.use_count() = 1
bp2.use_count() = 1
Bad::~Bad() called
Bad::~Bad() called
mytext(59120,0x1196ace00) malloc: *** error for object 0x7fc860405b20: pointer being freed was not allocated
mytext(59120,0x1196ace00) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      ./mytext

注意上面的析构调用了两次
```

正确的使用方式:
```cxx
#include <memory>
#include <iostream>

struct Good : std::enable_shared_from_this<Good> { // 注意：继承
public:
    std::shared_ptr<Good> getptr() {
        return shared_from_this();
    }
    ~Good() {
        std::cout << "Good::~Good() called" << std::endl;
    }
};

int main() {
    // 大括号用于限制作用域，这样智能指针就能在system("pause")之前析构
    {
        std::shared_ptr<Good> gp1(new Good());
        std::shared_ptr<Good> gp2 = gp1->getptr();
        // 打印gp1和gp2的引用计数
        std::cout << "gp1.use_count() = " << gp1.use_count() << std::endl;
        std::cout << "gp2.use_count() = " << gp2.use_count() << std::endl;
    }
    system("pause");
}

运行结果:
gp1.use_count() = 2
gp2.use_count() = 2
Good::~Good() called

```



